ARG BASE_IMAGE=golang:1.20.2
FROM ${BASE_IMAGE} AS builder

WORKDIR /go/src/woongkie-talkie

COPY go.* ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=1 go build -o /go/bin/woongkie-talkie

ARG BASE_IMAGE=gcr.io/distroless/base-debian11
FROM ${BASE_IMAGE}

ENV GOPATH /go

COPY ./view /go/src/woongkie-talkie/view

COPY --from=builder /go/bin/woongkie-talkie /
COPY .env /go/src/woongkie-talkie/.env

EXPOSE 8080

CMD ["/woongkie-talkie", "serve"]